### ISSUE TITLE
Estructuración del repositorio

### ISSUE THREAD

**Issue by Yared70** [Alejandrotr22/TCNoviembre_Toste_Yared#1]
Creación de la tabla Scrum del proyecto

**Comment by Yared70** [comment]
Es necesario poner el repositorio como público para poder tener Wiki

**Comment by Alejandrotr22** [comment]
> Es necesario poner el repositorio como público para poder tener Wiki

Repositorio ha sido cambiado a publico

**Comment by Alejandrotr22** [comment]
Tablas de Scrum del Proyecto creado y estructurado
