### ISSUE TITLE
Creación del modelo Entidad-Relacion

### ISSUE THREAD

**Issue by Yared70** [Alejandrotr22/TCNoviembre_Toste_Yared#2]
Creación del modelo entidad-relacion en la página drawsql y añadirlo a la wiki

Enlace al modelo en drawsql: [diagrama](https://drawsql.app/teams/dev70/diagrams/tcpaginaapuestas)

**Comment by Yared70** [comment]
Creada y conectada la branch feature_2 para trabajar en esta issue

**Comment by Alejandrotr22** [comment]
Hay que cambiar ciertos parametros en el diagrama, la fecha final en eventos no debe ser not null, incrementar el varchar del nombre del equipo, añadir el saldo en el usuario y poner sus atributos en español

**Comment by Alejandrotr22** [comment]
Eliminar relación entre apuestas y equipos

**Comment by Alejandrotr22** [comment]
Añadir Campo de estado a la apuesta
