### ISSUE TITLE
Creación del diagrama de casos de uso

### ISSUE THREAD

**Issue by Alejandrotr22** [Alejandrotr22/TCNoviembre_Toste_Yared#3]
# Creación del diagrama de casos de uso para la aplicación de las apuestas de deportes

### Usuario
> * Registro/login usuario
> * Elegir Deporte
> * Elegir evente
> * Realizar apuesta
> * Visualizar perfil

### Administrador
> * login Admin
> * Elegir Deporte
> * Crear Evento
> * Finalizar Evento
> * Comprprobar evento

**Comment by Alejandrotr22** [comment]
Falta añadir la información en la wiki

**Comment by Yared70** [comment]
Añadida a la wiki y al readme el diagrama de casos de uso
